name: soulie
description: "Soulie - Photo Sharing App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  # Router
  go_router: ^15.1.2

  # Google Fonts
  google_fonts: ^6.2.1

  # Utils
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  http: ^1.6.0
  home_widget: ^0.9.0
  camera: ^0.12.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
